### PR TITLE
1.x coverity fixups

### PR DESCRIPTION
**Pull request by flihp**

### CODE REVIEW

**Comment by flihp** [comment]
If it's easier on the eyes we can always do the check in the loop after the call to the marshalling function and break out of the loop if there's an RC in rval `!= TSS2_RC_SUCCESS`. I try to avoid `break` if possible though so I went with using the loop terminating condition.

**Comment by tstruk** [comment]
We could just return, but thinking about it now - are we not supposed to reset the SYS_CONTEXT->nextData to what in was at the fn entry in case of an error in the middle of (un)marshaling? The new MU spec requires the implementation to do so.

**Comment by flihp** [comment]
Like you say, there's nothing that requires we do so until the libmu code. I'd say we should minimize the changes we make here to keep the behavior consistent. All of this will be fixed in 2.0.

**Comment by tstruk** [comment]
ok, so that should do it.

**Pull request merged**
