### PR TITLE
Add support for code-coverage

### PR DESCRIPTION
**Pull request by AndreasFuchsSIT**
Add support for code coverage measurement.

Also a minor tweak to build check_PROGRAMS independently running them.

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
Ok, so travis-ci does not support this...
Under Ubuntu ax_code_coverage.m4 is part of autoconf-archive

**Comment by flihp** [comment]
It's not pretty, but downloading an autoconf-archive release tarball (much in the same way we do the tpm2 simulator) is probably your best bet here.

**Comment by AndreasFuchsSIT** [comment]
Either that or adding the m4 macro into the m4/ directory.
However that macro is apparently under LGPL...
Can we deal with multi-license in this project ?

**Comment by martinezjavier** [comment]
@AndreasFuchsSIT that's a very good point. I think the answer then is that we can't include the macro it in the project repo...

The opposite wouldn't have been a problem (if tpm2-tss was licensed under LGPL and the autoconf macro was licensed under BSD 2-clause) since the derivative work would still had been LGPL.

So @flihp proposed workaround seems like the best way to solve this for me.

**Comment by AndreasFuchsSIT** [comment]
In that case, I have a script for travis:
```
wget http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2017.09.28.tar.xz
sha256sum autoconf-archive-2017.09.28.tar.xz | grep -q 5c9fb5845b38b28982a3ef12836f76b35f46799ef4a2e46b48e2bd3c6182fa01
tar xJf autoconf-archive-2017.09.28.tar.xz
cp autoconf-archive-2017.09.28/m4/ax_code_coverage.m4 m4/
```

**Comment by AndreasFuchsSIT** [comment]
Sorry, I was unaware of the .travis.yml file...
Test is working now...

**Pull request merged**
